# Default configuration for Xtensa

CONFIG_SEMIHOSTING=y

# Boards:
#
CONFIG_XTENSA_SIM=y
CONFIG_XTENSA_VIRT=y
CONFIG_XTENSA_XTFPGA=y
CONFIG_SSP=y
CONFIG_SAI=y
CONFIG_DW_DMA_DSP=y
CONFIG_EDMA_DSP=y
CONFIG_SDMA_DSP=y 
CONFIG_HDA_DMA_DSP=y
CONFIG_ADSP_DSP=y
